// Audiobook player — exposed as window.AudioPlayer.
// Loaded as a plain script (no ES modules) to match main.js / comments.js conventions.
//
// Data comes from audio/manifest.json (generated by build_audio.py). One shared <audio>
// element streams per-chapter MP3s from the R2 origin in the manifest; a persistent
// sticky #mini-player survives drawer open/close and scrolling. All durable state is the
// last position per language in localStorage — there is no server component.
(function () {
  "use strict";

  const MANIFEST_URL = "audio/manifest.json";
  const POS_KEY_PREFIX = "audioPos_"; // audioPos_{lang} -> {pos, time}
  const SPEEDS = [1, 1.25, 1.5, 1.75, 2];

  // Media-control icons are painted by CSS as SVG masks over currentColor (see
  // the .audio-play-btn / .mp-btn ::before rules in styles.css), NOT as font
  // glyphs. The previous text-glyph + U+FE0E approach was unreliable on
  // iOS/Android, which ignored the selector and swapped in color emoji. So these
  // buttons carry NO text content; their visual state is driven purely by the
  // `is-playing` class, which flips the play triangle to pause bars.

  const I18N = {
    de: {
      comingSoon: "Das Hörbuch erscheint bald.",
      downloadAll: "Alle Kapitel herunterladen (ZIP)",
      play: "Abspielen",
      pause: "Pause",
      download: "Herunterladen",
      prev: "Vorheriges Kapitel",
      next: "Nächstes Kapitel",
      close: "Player schließen",
      speed: "Geschwindigkeit",
      loadError: "Hörbuch konnte nicht geladen werden.",
    },
    en: {
      comingSoon: "The audiobook is coming soon.",
      downloadAll: "Download all chapters (ZIP)",
      play: "Play",
      pause: "Pause",
      download: "Download",
      prev: "Previous chapter",
      next: "Next chapter",
      close: "Close player",
      speed: "Speed",
      loadError: "Could not load the audiobook.",
    },
    ru: {
      comingSoon: "Аудиокнига скоро появится.",
      downloadAll: "Скачать все главы (ZIP)",
      play: "Слушать",
      pause: "Пауза",
      download: "Скачать",
      prev: "Предыдущая глава",
      next: "Следующая глава",
      close: "Закрыть плеер",
      speed: "Скорость",
      loadError: "Не удалось загрузить аудиокнигу.",
    },
  };

  // --- module state ---
  let manifest = null;
  let manifestError = false;
  let currentLang = "de";
  let contentEl = null; // .drawer-content of #drawer-audio
  let miniEl = null; // #mini-player container
  let getLang = () => currentLang;

  const audio = new Audio();
  audio.preload = "metadata";

  let currentPos = -1; // index into the current language's chapters[] (NOT chapter.index)
  let speedIdx = 0;
  let saveTimer = null;

  // mini-player sub-elements (created once)
  let mp = null;

  // --- helpers ---
  function t() {
    return I18N[currentLang] || I18N.en;
  }

  function chaptersForLang(lang) {
    const block = manifest && manifest.langs && manifest.langs[lang];
    return block && Array.isArray(block.chapters) ? block.chapters : [];
  }

  function urlFor(ch) {
    const base = (manifest.baseUrl || "").replace(/\/+$/, "");
    return base ? `${base}/${ch.file}` : ch.file;
  }

  function fmtClock(sec) {
    sec = Math.max(0, Math.floor(sec || 0));
    const h = Math.floor(sec / 3600);
    const m = Math.floor((sec % 3600) / 60);
    const s = sec % 60;
    const mm = h ? String(m).padStart(2, "0") : String(m);
    return (h ? h + ":" : "") + mm + ":" + String(s).padStart(2, "0");
  }

  function el(tag, attrs, text) {
    const node = document.createElement(tag);
    if (attrs) {
      for (const k in attrs) {
        if (k === "class") node.className = attrs[k];
        else node.setAttribute(k, attrs[k]);
      }
    }
    if (text != null) node.textContent = text;
    return node;
  }

  // --- chapter list (drawer) ---
  function renderList() {
    if (!contentEl) return;
    contentEl.innerHTML = "";

    if (manifestError) {
      contentEl.appendChild(el("p", { class: "audio-empty" }, t().loadError));
      return;
    }
    const chapters = chaptersForLang(currentLang);
    if (!chapters.length) {
      contentEl.appendChild(el("p", { class: "audio-empty" }, t().comingSoon));
      return;
    }

    const block = manifest.langs[currentLang];

    // Header actions: optional download-all
    const actions = el("div", { class: "audio-actions" });
    if (block.zip) {
      actions.appendChild(el("a", { class: "audio-action-link", href: urlFor({ file: block.zip }), download: "" }, t().downloadAll));
    }
    contentEl.appendChild(actions);

    const list = el("div", { class: "audio-list" });
    chapters.forEach((ch, pos) => {
      const row = el("div", { class: "audio-row", "data-pos": String(pos) });

      const playBtn = el("button", { class: "audio-play-btn", type: "button", "aria-label": `${t().play}: ${ch.title}` });
      playBtn.addEventListener("click", () => toggleChapter(pos));

      const main = el("div", { class: "audio-row-main" });
      main.appendChild(el("span", { class: "audio-row-title" }, ch.title));
      main.appendChild(el("span", { class: "audio-row-dur" }, fmtClock(ch.duration)));

      const dl = el("a", { class: "audio-dl", href: urlFor(ch), download: "", "aria-label": `${t().download}: ${ch.title}` }, "⤓");

      row.appendChild(playBtn);
      row.appendChild(main);
      row.appendChild(dl);
      list.appendChild(row);
    });
    contentEl.appendChild(list);
    highlightRow();
  }

  function highlightRow() {
    if (!contentEl) return;
    contentEl.querySelectorAll(".audio-row").forEach((row) => {
      const isActive = Number(row.dataset.pos) === currentPos;
      row.classList.toggle("active", isActive);
      const btn = row.querySelector(".audio-play-btn");
      if (btn) {
        const playing = isActive && !audio.paused;
        btn.classList.toggle("is-playing", playing);
      }
    });
  }

  // --- mini-player ---
  function buildMini() {
    if (!miniEl || mp) return;
    miniEl.innerHTML = "";
    const inner = el("div", { class: "mp-inner" });

    const prev = el("button", { class: "mp-btn mp-prev", type: "button", "aria-label": t().prev });
    const play = el("button", { class: "mp-btn mp-play", type: "button", "aria-label": t().play });
    const next = el("button", { class: "mp-btn mp-next", type: "button", "aria-label": t().next });

    const meta = el("div", { class: "mp-meta" });
    const title = el("div", { class: "mp-title" }, "");
    const seekRow = el("div", { class: "mp-seekrow" });
    const seek = el("input", { class: "mp-seek", type: "range", min: "0", max: "1000", value: "0", "aria-label": "Seek" });
    const time = el("span", { class: "mp-time" }, "0:00 / 0:00");
    seekRow.appendChild(seek);
    seekRow.appendChild(time);
    meta.appendChild(title);
    meta.appendChild(seekRow);

    const speed = el("button", { class: "mp-btn mp-speed", type: "button", "aria-label": t().speed }, "1×");
    const close = el("button", { class: "mp-btn mp-close", type: "button", "aria-label": t().close }, "×");

    inner.append(prev, play, next, meta, speed, close);
    miniEl.appendChild(inner);

    mp = { play, prev, next, title, seek, time, speed, close };

    play.addEventListener("click", togglePlay);
    prev.addEventListener("click", () => skip(-1));
    next.addEventListener("click", () => skip(1));
    close.addEventListener("click", closeMini);
    speed.addEventListener("click", cycleSpeed);

    let seeking = false;
    seek.addEventListener("input", () => {
      seeking = true;
      if (audio.duration) {
        const target = (Number(seek.value) / 1000) * audio.duration;
        mp.time.textContent = `${fmtClock(target)} / ${fmtClock(audio.duration)}`;
      }
    });
    seek.addEventListener("change", () => {
      if (audio.duration) audio.currentTime = (Number(seek.value) / 1000) * audio.duration;
      seeking = false;
    });
    mp._isSeeking = () => seeking;
  }

  function showMini() {
    if (miniEl) miniEl.hidden = false;
    document.body.classList.add("mini-player-open");
  }
  function closeMini() {
    audio.pause();
    if (miniEl) miniEl.hidden = true;
    document.body.classList.remove("mini-player-open");
    highlightRow();
  }

  // --- playback ---
  function loadChapter(pos, autoplay, atTime) {
    const chapters = chaptersForLang(currentLang);
    if (pos < 0 || pos >= chapters.length) return;
    currentPos = pos;
    const ch = chapters[pos];
    if (!audio.src || decodeURI(audio.src) !== decodeURI(urlFor(ch))) {
      audio.src = urlFor(ch);
    }
    audio.playbackRate = SPEEDS[speedIdx];
    buildMini();
    if (mp) mp.title.textContent = ch.title;
    showMini();
    if (typeof atTime === "number" && atTime > 0) {
      const seekTo = () => {
        try { audio.currentTime = atTime; } catch (e) { /* metadata not ready */ }
        audio.removeEventListener("loadedmetadata", seekTo);
      };
      if (audio.readyState >= 1) seekTo();
      else audio.addEventListener("loadedmetadata", seekTo);
    }
    if (autoplay) audio.play().catch(() => {});
    highlightRow();
  }

  function toggleChapter(pos) {
    if (pos === currentPos) {
      togglePlay();
    } else {
      loadChapter(pos, true, 0);
    }
  }

  function togglePlay() {
    if (currentPos < 0) return;
    if (audio.paused) audio.play().catch(() => {});
    else audio.pause();
  }

  function skip(delta) {
    const chapters = chaptersForLang(currentLang);
    const target = currentPos + delta;
    if (target >= 0 && target < chapters.length) loadChapter(target, true, 0);
  }

  function cycleSpeed() {
    speedIdx = (speedIdx + 1) % SPEEDS.length;
    audio.playbackRate = SPEEDS[speedIdx];
    if (mp) mp.speed.textContent = SPEEDS[speedIdx] + "×";
  }

  function persist() {
    if (currentPos < 0) return;
    try {
      localStorage.setItem(
        POS_KEY_PREFIX + currentLang,
        JSON.stringify({ pos: currentPos, time: Math.floor(audio.currentTime || 0) })
      );
    } catch (e) { /* ignore quota/private-mode */ }
  }

  function restore() {
    const chapters = chaptersForLang(currentLang);
    if (!chapters.length) return;
    let saved = null;
    try { saved = JSON.parse(localStorage.getItem(POS_KEY_PREFIX + currentLang) || "null"); } catch (e) {}
    if (saved && Number.isInteger(saved.pos) && saved.pos >= 0 && saved.pos < chapters.length) {
      loadChapter(saved.pos, false, saved.time || 0); // cue, paused — "continue listening"
    }
  }

  // --- audio element events ---
  audio.addEventListener("play", () => { highlightRow(); if (mp) { mp.play.classList.add("is-playing"); mp.play.setAttribute("aria-label", t().pause); } });
  audio.addEventListener("pause", () => { highlightRow(); if (mp) { mp.play.classList.remove("is-playing"); mp.play.setAttribute("aria-label", t().play); } persist(); });
  audio.addEventListener("ended", () => { persist(); skip(1); });
  audio.addEventListener("timeupdate", () => {
    if (mp && audio.duration) {
      if (!mp._isSeeking || !mp._isSeeking()) {
        mp.seek.value = String(Math.round((audio.currentTime / audio.duration) * 1000));
        mp.time.textContent = `${fmtClock(audio.currentTime)} / ${fmtClock(audio.duration)}`;
      }
    }
    clearTimeout(saveTimer);
    saveTimer = setTimeout(persist, 2000);
  });

  async function loadManifest() {
    if (manifest || manifestError) return;
    try {
      const res = await fetch(MANIFEST_URL, { cache: "no-cache" });
      if (!res.ok) throw new Error("manifest " + res.status);
      manifest = await res.json();
    } catch (e) {
      manifestError = true;
    }
  }

  // --- public API (mirrors window.CommentsUI) ---
  const AudioPlayer = {
    async init(opts) {
      opts = opts || {};
      contentEl = opts.contentEl || (opts.drawerEl && opts.drawerEl.querySelector(".drawer-content")) || null;
      miniEl = opts.miniEl || document.getElementById("mini-player");
      getLang = opts.getCurrentLang || getLang;
      currentLang = getLang();
      await loadManifest();
      restore();
    },
    async open() {
      await loadManifest();
      currentLang = getLang();
      renderList();
    },
    setLang(lang) {
      if (lang === currentLang) return;
      // Stop playback when switching languages — chapter sets differ per language.
      audio.pause();
      audio.removeAttribute("src");
      audio.load();
      currentPos = -1;
      currentLang = lang;
      if (miniEl) { miniEl.hidden = true; document.body.classList.remove("mini-player-open"); }
      renderList();
      restore();
    },
  };

  window.AudioPlayer = AudioPlayer;
})();
